#!/bin/sh

if [ -d /mnt/shared ]; then
    find /mnt/shared -name 'pg-*.tgz' -printf "%T@ %p\n" | sort -nr | head -1 | cut -d\  -f2
else
    find /tmp -name 'pg-*.tgz' -printf "%T@ %p\n" | sort -nr | head -1 | cut -d\  -f2
fi
